services:
  - type: static
    name: ChatFire
    buildCommand: npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm --filter @workspace/chatfire run build:render
    staticPublishPath: artifacts/chatfire/dist/public
    pullRequestPreviewsEnabled: false
    branch: main
