services:
  - type: static
    name: ChatFire
    buildCommand: cd artifacts/chatfire && npm install && npx vite build --config vite.config.render.ts
    staticPublishPath: artifacts/chatfire/dist/public
    pullRequestPreviewsEnabled: false
    branch: main
